### ISSUE TITLE
Cookie set on server cannot be read on server returns undefined

### ISSUE THREAD

**Issue by Surbhi77** [salemdar/ngx-cookie#171]
The cookie set on server side in universal, returns undefined when read on server side

**Comment by salemdar** [comment]
It should be fixed now.

**Comment by Muzummil** [comment]
Still happening for me with versions 
"ngx-cookie": "^5.0.2",
"ngx-cookie-backend": "^5.0.2"
